Repository ConnorAndersonLarson/PlanetParty, pull requests merged in 2021-04, with the labels that each got.

#23 Feature/all planets view
  package-lock.json
  src/App.tsx
  src/Planet/Planet.tsx
  src/Planet/planet-images/earth.svg
  src/Planet/planet.css
  src/Planetarium/Planetarium.tsx
  src/Planetarium/planetarium.css
Labels: React, TypeScript, enhancement

#30 Feature/planet detail
  src/apiCalls.js
  src/components/App/App.tsx
  src/components/Planet/Planet.tsx
  src/components/Planet/planet.css
  src/components/PlanetInfo/PlanetInfo.tsx
  src/components/PlanetInfo/planetInfo.css
  src/components/Planetarium/Planetarium.tsx
  src/components/Planetarium/planetarium.css
  src/components/SortBox/SortBox.tsx
  src/data/planetData.js
  src/interface.ts
Labels: React, TypeScript, User Stories, enhancement

#33 Style/responsiveness sort box
  public/space/asteroid.png
  public/space/eclipse.png
  public/space/laws.png
  public/space/orbit.png
  public/space/solar-system.png
  public/space/sun.png
  src/components/Planet/planet.css
  src/components/PlanetInfo/PlanetInfo.tsx
  src/components/PlanetInfo/planetInfo.css
  src/components/Planetarium/planetarium.css
  src/components/SortBox/SortBox.css
  src/components/SortBox/SortBox.tsx
Labels: Styling

#36 Fix interface imports, and passing down sortPlanet prop to components
  package-lock.json
  src/components/App/App.tsx
  src/components/Planetarium/Planetarium.tsx
  src/interface.ts
Labels: documentation

#40 Refactor/remove test data from app
  src/components/App/App.tsx
  src/components/Planet/Planet.tsx
  src/components/Planetarium/Planetarium.tsx
  src/components/SortBox/SortBox.tsx
Labels: React, Styling, TypeScript

#47 Refactor/extend testing
  cypress/fixtures/testPlanets.json
  cypress/integration/main-page.js
  cypress/integration/single-planet.js
  cypress/integration/sort-page.js
  src/components/Planet/Planet.tsx
Labels: Testing, enhancement

#48 Refactor/router add switch
  src/components/App/App.tsx
  src/components/PlanetInfo/PlanetInfo.tsx
Labels: React, TypeScript, bug

#53 Refactor/cleanup
  cypress/integration/api-test.js
  public/space/asteroid.png
  public/space/comet.png
  public/space/solar-system.png
  src/components/App/App.tsx
  src/components/Planet/Planet.tsx
  src/components/PlanetInfo/PlanetInfo.tsx
  src/components/SortBox/SortBox.tsx
  src/interface.ts
Labels: enhancement

#52 Testing/api testing
  cypress/integration/api-test.js
Labels: Testing, enhancement

#54 Feature/edit text single planet
  src/components/PlanetInfo/PlanetInfo.tsx
  src/components/PlanetInfo/planetInfo.css
Labels: React, Styling, TypeScript, User Stories

#55 Refactor/responsiveness
  src/components/Header/Header.css
  src/components/Planet/Planet.tsx
  src/components/Planet/planet.css
  src/components/SortBox/SortBox.css
Labels: Styling, enhancement

#56 Fix/sort buttons add commas
  src/components/App/App.tsx
  src/components/Planet/Planet.tsx
  src/components/PlanetInfo/PlanetInfo.tsx
  src/components/Planetarium/Planetarium.tsx
  src/components/SortBox/SortBox.tsx
  src/interface.ts
Labels: React, TypeScript

#69 Fix/change src paths
  src/components/Planet/Planet.tsx
  src/components/PlanetInfo/PlanetInfo.tsx
Labels: React

#70 Fix/gravity input
  src/components/PlanetInfo/PlanetInfo.tsx
  src/components/PlanetInfo/planetInfo.css
Labels: React, TypeScript

#72 Styling/planet cards
  src/components/App/App.tsx
  src/components/Planet/Planet.tsx
  src/components/Planet/planet.css
Labels: Styling, enhancement

#74 Testing/single page
  cypress/integration/main-page.js
  cypress/integration/single-planet.js
  cypress/integration/sort-page.js
  src/components/PlanetInfo/PlanetInfo.tsx
Labels: Testing, enhancement

#76 Refactor styling to adjust for contrast errors and header height
  src/components/Header/Header.css
  src/components/PlanetInfo/planetInfo.css
  src/components/SortBox/SortBox.css
Labels: Styling, bug, enhancement
